@baseUrl = https://8080-dennisfaria-aulaarquite-uzgf3oncrn2.ws-us115.gitpod.io

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgVGFyZWZhcyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzI1MzE2MDkwfQ.NTx2ZmR2G3_rcfhWp9PnTJi6Rc0Yp79sJczrc02ZFK8

###
GET {{baseUrl}}/tarefas

###
POST {{baseUrl}}/tarefas
Authorization: Bearer{{token}}
Content-Type: application/json

{
    "descricao": "Criar Formulário",
    "concluido": false
}

###
GET {{baseUrl}}/tarefas/4

###
PUT {{baseUrl}}/tarefas/1
Content-Type: application/json

{
    "descricao": "Testando Alteração",
    "concluido": false
}

###
DELETE {{baseUrl}}/tarefas/1